# Generated by Django 5.0.3 on 2024-04-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='satilikTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilanNo', models.IntegerField(default=0)),
                ('sokak', models.CharField(max_length=15)),
                ('fiyat', models.IntegerField(null=True)),
                ('m2', models.IntegerField(null=True)),
                ('aktiflik', models.BooleanField(null=True)),
                ('odaSayi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='satilikDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binaYas', models.IntegerField(null=True)),
                ('katSayi', models.IntegerField(null=True)),
                ('kat', models.IntegerField(null=True)),
                ('isitma', models.CharField(max_length=20)),
                ('ilanTarih', models.DateField(null=True)),
                ('tapuDurum', models.CharField(max_length=20)),
                ('esya', models.CharField(max_length=20)),
                ('asonsor', models.CharField(max_length=20)),
                ('balkon', models.CharField(max_length=20)),
                ('otopark', models.CharField(max_length=20)),
                ('aidat', models.IntegerField(null=True)),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kullanici', to='satilikdaireler.satiliktakip')),
            ],
        ),
    ]
