# Generated by Django 5.0.3 on 2024-05-13 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='satilikTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilanNo', models.IntegerField(default=0)),
                ('sokak', models.CharField(max_length=15)),
                ('fiyat', models.IntegerField(null=True)),
                ('m2', models.IntegerField(null=True)),
                ('aktiflik', models.BooleanField(null=True)),
                ('odaSayi', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='satilikResim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='satilik_images/')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resimler', to='satilikdaireler.satiliktakip')),
            ],
        ),
        migrations.CreateModel(
            name='satilikDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binaYas', models.IntegerField(null=True)),
                ('katSayi', models.IntegerField(null=True)),
                ('kat', models.IntegerField(null=True)),
                ('isitma', models.CharField(max_length=20)),
                ('ilanTarih', models.DateField(null=True)),
                ('tapuDurum', models.CharField(max_length=20)),
                ('esya', models.CharField(max_length=20)),
                ('asonsor', models.CharField(max_length=20)),
                ('balkon', models.CharField(max_length=20)),
                ('otopark', models.CharField(max_length=20)),
                ('aidat', models.IntegerField(null=True)),
                ('kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kullanici', to='satilikdaireler.satiliktakip')),
            ],
        ),
        migrations.CreateModel(
            name='Favoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_favori', to=settings.AUTH_USER_MODEL)),
                ('satilik_ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favori_ilan', to='satilikdaireler.satiliktakip')),
            ],
            options={
                'unique_together': {('kullanici', 'satilik_ilan')},
            },
        ),
    ]
