# Generated by Django 5.0.3 on 2024-05-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('deger', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tarih', models.DateField()),
            ],
        ),
    ]
